[package]

name = "inventory_watcher"
version = "0.0.1"
authors = [ "Giovanni Frank Crisanti <you@example.com>" ]

[[bin]]

name = "server"

[dependencies]
iron = "*"
rustc-serialize = "*"
router = "*"
hyper = "*"

[dependencies.mysql]
default-features = false
features = ["pipe"]